[Added] First simple sample - AS3 pure code only [Updated] Now the ArrayHeap keeps the order of the added file [Added] New shell script to build the samples [Added] Resources for the samples

diff --git a/trunk/bin/generate-swc b/trunk/bin/generate-swc
--- a/trunk/bin/generate-swc
+++ b/trunk/bin/generate-swc
@@ -1,19 +1,29 @@
 #!/bin/sh
 
-cd `dirname $0`
+dir_name=`dirname $0`
+cmd_name=`basename $0`
 
-source config
-cd ..
+source "$dir_name/config"
+cd "$dir_name/.."
 
-current_revision=`svn info | grep Revision | grep -o -E [0-9]+`
-echo -n "Enter revision (current=$current_revision) : "
-read revision
+temp_name="masapi-tmp.swc"
+file_name="$default_output_swc"
 
-file_name="masapi-2.0-r$revision.swc"
+if [ $# -eq 1 ]; then
+	if [ "$1" = "-help" ]; then
+		echo "Usage : $cmd_name [swc_path_name]"
+		exit
+	else
+		file_name=$1
+	fi
+elif [ $# -gt 1 ]; then
+	echo "Invalid number of arguments..." >&2
+	echo "Usage : $cmd_name [swc_path_name]"
+	exit
+fi
 
-command_line="$flex_sdk_path/compc -include-sources $source_path -output bundles/svn/$file_name -strict -optimize"
-echo $command_line
+echo "Generating $file_name..."
+$flex_sdk_path/compc -include-sources "$source_path/ch" -output "$temp_name" -strict -optimize
+mv "$temp_name" "$current_folder/$file_name"
 
-$command_line
-svn add bundles/svn/$file_name
-
+echo "The file $file_name has been successfully generated !"
